---
title: "Individual 1"
author: "Tim Potter"
date: "March 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyverse)
defense <- read_excel('C:/Users/tdpot/Documents/homework/ds202/ds202_lab4/cyclonesFootball2018.xlsx', sheet='Defensive')
str(defense)
offense <- read_excel('C:/Users/tdpot/Documents/homework/ds202/ds202_lab4/cyclonesFootball2018.xlsx', sheet='Offensive')
str(offense)
biography <- read_excel('C:/Users/tdpot/Documents/homework/ds202/ds202_lab4/cyclonesFootball2018.xlsx', sheet='Biography')
str(biography)
```

## Cleaning

```{r}
defClean <- defense %>%
  mutate(Tackles_Solo = as.numeric(Tackles_Solo),
         Tackles_ASST = as.numeric(Tackles_ASST),
         Tackles_Sack = as.numeric(Tackles_Sack),
         Tackles_TFL = as.numeric(Tackles_TFL),
         Turnover_FF = as.numeric(Turnover_FF),
         Turnover_FR = as.numeric(Turnover_FR),
         Turnover_INT = as.numeric(Turnover_INT),
         Pass_QBH = as.numeric(Pass_QBH),
         Pass_PB = as.numeric(Pass_PB))
defClean <- defClean %>%
  rename(Opponent=Opponent_Opponent) %>%
  mutate(Opponent = factor(Opponent))
defClean <- defClean %>%
  mutate(Name = factor(Name))
str(defClean)


offClean <- offense %>%
  rename(Opponent=Opponent_Opponent) %>%
  mutate(Opponent = factor(Opponent))
offClean <- offClean %>%
  mutate(Name = factor(Name))
offClean <- offClean %>%
  mutate(Receiving_REC = as.numeric(Receiving_REC),
         Receiving_YDS = as.numeric(Receiving_YDS),
         Receiving_TD = as.numeric(Receiving_TD),
         Rushing_ATT = as.numeric(Rushing_ATT),
         Rushing_YDS = as.numeric(Rushing_YDS),
         Rushing_TD = as.numeric(Rushing_TD),
         Passing_YDS = as.numeric(Passing_YDS),
         Passing_TD = as.numeric(Passing_TD),
         Passing_INT = as.numeric(Passing_INT))
offClean <- offClean %>%
  separate(`Passing_CMP-ATT`, into = (c("Passing_CMP", "Passing_ATT")))
offClean[is.na(offClean)] <- 0
offClean <- offClean %>%
  mutate(Passing_CMP = as.numeric(Passing_CMP),
         Passing_ATT = as.numeric(Passing_ATT))
str(offClean)

bioClean <- biography %>%
  mutate(Name = factor(Name),
         Weight = as.numeric(Weight))
bioClean$Height <- sapply(strsplit(as.character(bioClean$Height),"-"),
        function(x){12*as.numeric(x[1]) + as.numeric(x[2])})
str(bioClean)
```
